version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Tag }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64

archives:
  - format: zip
    name_template: "azpim-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  generate_release_notes: true
